### ISSUE TITLE
Document which JSON Schema draft version is supported.

### ISSUE THREAD

**Issue by alexanderkjeldaas** [java-json-tools/json-schema-core#17]
A lot of JSON Schema software only supports version 3, so this is probably the single most important piece of information to put in README.md.

**Comment by daveclayton** [comment]
HI @alexanderkjeldaas is this issue still valid?

**Comment by huggsboson** [comment]
I believe v3 and v4 are supported.  Would love to accept a patch to support v5 and v6.
