### ISSUE TITLE
guava call causing dependency issues

### ISSUE THREAD

**Issue by ajhcpt** [java-json-tools/json-schema-core#41]
Hi, this call in BaseSchemaTree:
```java
public final String toString()
    {
        return Objects.toStringHelper(this)
            .add("key", key)
            .add("pointer", pointer)
            .add("URI context", currentRef)
            .toString();
    }
```
Objects.toStringHelper has been deprecated and removed in later versions of guava. Is there another way to generate this string that doesn't depend on the Objects.toString?

**Comment by huggsboson** [comment]
similar to:
https://github.com/java-json-tools/jackson-coreutils/pull/1/files

**Comment by huggsboson** [comment]
PTAL at https://github.com/java-json-tools/json-schema-core/pull/42

**Comment by huggsboson** [comment]
json-schema-core 1.2.10 and json-schema-validator 2.2.10 should be out soon with this fix.
