### ISSUE TITLE
Bintray link is broken

### ISSUE THREAD

**Issue by zarub2k** [java-json-tools/json-schema-core#43]
As per the documentation I tried to download the jar from bintray but this is broken https://bintray.com/java-json-tools/maven/json-schema-core Can you tell me where is the official jar available for my usage?

**Comment by Capstan** [comment]
The Maven Central link is https://repo1.maven.org/maven2/com/github/java-json-tools/json-schema-core/. It looks like the Bintray link moved to https://bintray.com/bintray/jcenter/com.github.java-json-tools%3Ajson-schema-core.
