### ISSUE TITLE
Question about intended license

### ISSUE THREAD

**Issue by swinslow** [java-json-tools/json-schema-core#47]
Hello, I'm working with some other FOSS projects that are looking at using some of the java-json-tools projects as dependencies.

Where it says that these repos are "dual licensed LGPLv3 or later/ASL 2.0", and also in the LICENSE files that they are "dual-licensed," I've interpreted that as meaning that these repos can be used under **either** LGPLv3 **or** ASL 2.0.

Can you confirm that that's the intent here? I've received questions about whether it instead means that downstream projects have to use the code under **both** LGPLv3 **and** ASL 2.0, and I don't think that's your intent. Grateful if you can confirm though. Thank you!

**Comment by huggsboson** [comment]
Here is the stance:
https://github.com/java-json-tools/json-schema-validator/issues/136

**Comment by swinslow** [comment]
Perfect, thank you!
